# Test description:
#   This test case checks the DDS Enabler receives the chatter topic published in ROS2 domain 0 (with no config file).

services:

  # ENABLER
  ddsenabler:
    image: ${DDSENABLER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsenabler
    networks:
      - std_net
    volumes:
      - ./config.json:/build/ddsenabler/examples/config.json
    command: ./build/ddsenabler/examples/ddsenabler_example 2 4 10

  talker:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: talker
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ../../scripts:/scripts
    command: ros2 topic pub /chatter std_msgs/msg/String "{}" --once --spin-time 3

networks:
  std_net:
  default:
    driver: none
