# Test description:
#   expected_types = 1
#   expected_topics = 1
#   expected_data = 1
#   timeout = 6
#   config_file_path_: allowed only /chatter topic
#   This test case checks the DDS Enabler, configured with a YAML file, receives only the chatter topic.
#   The chatter topic is published ROS2 domain 2 with 1 Hz rate.
#   It is checked that at least 3 messages are received in at most 6 seconds.

services:

  # ENABLER
  ddsenabler:
    image: ${DDSENABLER_COMPOSE_TEST_DOCKER_IMAGE}
    container_name: ddsenabler
    networks:
      - std_net
    volumes:
      - ./config.yml:/config/config.yml
    command: ./build/ddsenabler/examples/ddsenabler_example --config /config/config.yml --expected-types 1 --expected-topics 1 --expected-data 3 --timeout 6

  talker:
    image: ${DDSENABLER_COMPOSE_TEST_ROS2_DOCKER_IMAGE}
    container_name: talker
    depends_on:
      - ddsenabler
    networks:
      - std_net
    environment:
      - ROS_DOMAIN_ID=2
    volumes:
      - ../../../scripts:/scripts
    command: python3 /scripts/execute_and_validate_talker.py --timeout 6 --delay 1

networks:
  std_net:
  default:
    driver: none
