dds:
  domain: 0

  allowlist:
    - name: "topic_name"
    - name: "HelloWorldTopic"
      type: "HelloWorld"

  blocklist:
    - name: "topic_to_block"
      type: "type_to_block"

  topics:
    - name: "temperature/*"
      type: "temperature/types/*"
      qos:
        max-rx-rate: 15
        downsampling: 2

  ignore-participant-flags: filter_same_process
  transport: shm
  whitelist-interfaces:
    - "127.0.0.1"

ddsenabler:
  initial-publish-wait: 500
